--
-- DO NOT EDIT THIS FILE, your changes will be overwritten
-- This is an automatically generated file.
-- It was generated with uasm, the microassembler, on
-- Sat Aug 10 00:52:20 2019
--
--
-- component NRLT_microcode_rom
--   port( ADDR_IN  : in  std_logic_vector( 7 downto 0);
--         DATA_OUT : out std_logic_vector(31 downto 0));
-- end component;
--
--
-- This case statement was generated with the following
--   fields:
--
--  signal     DATA_OUT : std_logic_vector(31 downto 0);
--  signal         ASEL : std_logic_vector( 2 downto 0);
--  signal         BSEL : std_logic_vector( 2 downto 0);
--  signal         DSEL : std_logic_vector( 2 downto 0);
--  signal         SSEL : std_logic_vector( 3 downto 0);
--  signal         HSEL : std_logic_vector( 2 downto 0);
--  signal         MUX1 : std_logic;
--  signal         MUX2 : std_logic_vector( 2 downto 0);
--  signal         ADRS : std_logic_vector( 7 downto 0);
--  signal         MISC : std_logic_vector( 3 downto 0);
--
--
--                 ASEL <= DATA_OUT(31 downto 29);   -- bit size: 3
--                 BSEL <= DATA_OUT(28 downto 26);   -- bit size: 3
--                 DSEL <= DATA_OUT(25 downto 23);   -- bit size: 3
--                 SSEL <= DATA_OUT(22 downto 19);   -- bit size: 4
--                 HSEL <= DATA_OUT(18 downto 16);   -- bit size: 3
--                 MUX1 <= DATA_OUT(15);             -- bit size: 1
--                 MUX2 <= DATA_OUT(14 downto 12);   -- bit size: 3
--                 ADRS <= DATA_OUT(11 downto  4);   -- bit size: 8
--                 MISC <= DATA_OUT( 3 downto  0);   -- bit size: 4
--
-- Yeilding a total data width of 32 bits for 9 fields.
-- The maximum address encountered was 0xff, needing 8 bits
--
library ieee;
use ieee.std_logic_1164.ALL;

entity NRLT_microcode_rom is
port( ADDR_IN  : in  std_logic_vector( 7 downto 0);
      DATA_OUT : out std_logic_vector(31 downto 0));
end NRLT_microcode_rom;

architecture RTL of NRLT_microcode_rom is

   signal DATA_OUT_R : std_logic_vector(31 downto 0);
begin
   DATA_OUT <= DATA_OUT_R;

   process(ADDR_IN)
     begin
        case ADDR_IN is
          when "00000000" => DATA_OUT_R <= "00000000000000000000000000000000";
          -- START:
          when "00000001" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "00000010" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "00000011" => DATA_OUT_R <= "00000000000000000000000000001001";
          when "00000100" => DATA_OUT_R <= "00000000000000001001000000000000";
          when "00001000" => DATA_OUT_R <= "00100000100010000001000000010000";
          when "00010000" => DATA_OUT_R <= "00100000111100000001000000010000";
          when "00011000" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "00011001" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "00011010" => DATA_OUT_R <= "00000000100000000001000000010000";
          when "00100000" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "00100001" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "00100010" => DATA_OUT_R <= "00000100100100000001000000010000";
          when "00101000" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "00101001" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "00101010" => DATA_OUT_R <= "00000000000000000000000000000101";
          when "00101011" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "00101100" => DATA_OUT_R <= "00000000100000000001000000010000";
          when "00110000" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "00110001" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "00110010" => DATA_OUT_R <= "00000000000000000000000000000101";
          when "00110011" => DATA_OUT_R <= "00100000000000000000000000000010";
          when "00110100" => DATA_OUT_R <= "00100000000000000001000000010000";
          when "00111000" => DATA_OUT_R <= "00000000000000000000000000000000";
          when "00111001" => DATA_OUT_R <= "00000000000000000001000000010000";
          when "01000000" => DATA_OUT_R <= "00100000100000000100010000100000";
          when "01000001" => DATA_OUT_R <= "00000000000000000001000000010000";
          -- BE_Q:
          when "01000010" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "01000011" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "01000100" => DATA_OUT_R <= "00000011100000000001000000010000";
          when "01001000" => DATA_OUT_R <= "00000000000000000110010010100000";
          when "01001001" => DATA_OUT_R <= "00000000000000000001000000010000";
          -- BM_I:
          when "01001010" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "01001011" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "01001100" => DATA_OUT_R <= "00000011100000000001000000010000";
          when "01010000" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "01010001" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "01010010" => DATA_OUT_R <= "00000011100000000001000000010000";
          when "01011000" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "01011001" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "01011010" => DATA_OUT_R <= "00100000101010000001000000010000";
          when "01100000" => DATA_OUT_R <= "11000000000000000000000000000100";
          when "01100001" => DATA_OUT_R <= "11100000000010000000000000000010";
          when "01100010" => DATA_OUT_R <= "11100000000010000000000000000100";
          when "01100011" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "01100100" => DATA_OUT_R <= "00000011100000000000000000000000";
          when "01100101" => DATA_OUT_R <= "11000011000010000001000000010000";
          when "01101000" => DATA_OUT_R <= "11000011001100000000000000000000";
          when "01101001" => DATA_OUT_R <= "11000000000000000000000000000100";
          when "01101010" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "01101011" => DATA_OUT_R <= "00000011100000000001000000010000";
          when "01110000" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "01110001" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "01110010" => DATA_OUT_R <= "00000001000000000001000000010000";
          when "01111000" => DATA_OUT_R <= "01000001000010000001000000010000";
          when "10000000" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "10000001" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "10000010" => DATA_OUT_R <= "00000001100000000000000000000000";
          when "10000011" => DATA_OUT_R <= "01101010000100000000000000000000";
          when "10000100" => DATA_OUT_R <= "10000000000000000000000000000100";
          when "10000101" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "10000110" => DATA_OUT_R <= "00000100100100000001000000010000";
          when "10001000" => DATA_OUT_R <= "11100011100010000000000000000100";
          when "10001001" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "10001010" => DATA_OUT_R <= "00000001100000000000000000000000";
          when "10001011" => DATA_OUT_R <= "01101010000100000000000000000000";
          when "10001100" => DATA_OUT_R <= "10000000000000000000000000000100";
          when "10001101" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "10001110" => DATA_OUT_R <= "00100000101010000001000000010000";
          when "10010000" => DATA_OUT_R <= "11000000000000000000000000000100";
          when "10010001" => DATA_OUT_R <= "00100000000000000000000000000010";
          when "10010010" => DATA_OUT_R <= "11000011000010000001000000010000";
          when "10011000" => DATA_OUT_R <= "11000011001100000000000000000000";
          when "10011001" => DATA_OUT_R <= "11000000000000000000000000000100";
          when "10011010" => DATA_OUT_R <= "00000000000000000000000000000001";
          when "10011011" => DATA_OUT_R <= "00000000100000000001000000010000";
          when "11111111" => DATA_OUT_R <= "00000000000000000000000000000000";
          when others => DATA_OUT_R <= "00000000000000000000000000000000";
       end case;
     end process;
end RTL;
